### PR TITLE
go/client: make test more resilient

### LINKED ISSUE #1360: Go: TestAddChainRetries is flaky
```
=== RUN   TestAddChainRetries

2017/01/30 19:19:49 Request failed, backing-off for 1s: got HTTP status 503 Service Unavailable

2017/01/30 19:19:50 Request failed, backing-off for 2s: got HTTP status 503 Service Unavailable

2017/01/30 19:19:52 Request failed, backing-off for 4s: got HTTP status 503 Service Unavailable

2017/01/30 19:19:56 Request failed, backing-off for 5s: got HTTP status 503 Service Unavailable

2017/01/30 19:20:01 Request failed, backing-off for 10s: got HTTP status 503 Service Unavailable

2017/01/30 19:20:06 Request failed, backing-off for 1s: got HTTP status 503 Service Unavailable

2017/01/30 19:20:07 Request failed, backing-off for 1s: got HTTP status 503 Service Unavailable

2017/01/30 19:20:08 Request failed, backing-off for 1s: got HTTP status 503 Service Unavailable

2017/01/30 19:20:09 Request failed, backing-off for 1s: got HTTP status 503 Service Unavailable

2017/01/30 19:20:10 Request failed, backing-off for 1s: got HTTP status 503 Service Unavailable

2017/01/30 19:20:11 Request timed out, retrying immediately

2017/01/30 19:20:11 Request timed out, retrying immediately

2017/01/30 19:20:11 Request timed out, retrying immediately

2017/01/30 19:20:11 Request timed out, retrying immediately

2017/01/30 19:20:11 Request timed out, retrying immediately

2017/01/30 19:20:11 Request timed out, retrying immediately

2017/01/30 19:20:11 Request timed out, retrying immediately

2017/01/30 19:20:11 Request timed out, retrying immediately

2017/01/30 19:20:11 Request timed out, retrying immediately

2017/01/30 19:20:11 Request timed out, retrying immediately

--- FAIL: TestAddChainRetries (22.14s)

	logclient_test.go:262: #4 Submission took an unexpected length of time: 5.111453326s, expected ~5s

```

### PR DESCRIPTION
**Pull request by daviddrysdale**
Only fail the retry timing test if the difference in timings is
both:
 - more than 100ms out
 - more than 10% out.

Hopefully this will reduce test flakes and fix #1360.

### CODE REVIEW

File: go/client/logclient_test.go [hunk 1]
```diff
@@ -227,6 +227,7 @@ func TestAddChainRetries(t *testing.T) {
 		t.Fatalf("Failed to create client: %v", err)
 	}
 	leeway := time.Millisecond * 100
+	leewayRatio := 0.1 // 10%
 	instant := time.Millisecond
 	fiveSeconds := time.Second * 5
 	sevenSeconds := time.Second * 7 // = 1 + 2 + 4
```
Comment (RJPercival) [inline go/client/logclient_test.go]: All of the above 5 vars could be const.

File: go/client/logclient_test.go [hunk 2]
```diff
@@ -258,7 +259,9 @@ func TestAddChainRetries(t *testing.T) {
 		started := time.Now()
 		sct, err := client.AddChain(deadline, chain)
 		took := time.Since(started)
-		if math.Abs(float64(took-test.expected)) > float64(leeway) {
+		delta := math.Abs(float64(took - test.expected))
+		ratio := delta / float64(test.expected.Nanoseconds())
```
Comment (RJPercival) [inline go/client/logclient_test.go]: Why are you only calling Nanoseconds() here, and not on any of the other Durations? I believe it's effectively a no-op here anyway.

File: go/client/logclient_test.go (hunk 1 above)
Comment (daviddrysdale) [inline go/client/logclient_test.go]: True, done.

File: go/client/logclient_test.go (hunk 2 above)
Comment (daviddrysdale) [inline go/client/logclient_test.go]: Detritus from an earlier iteration where I was muddling units; removed.
