### PR TITLE
	Fix RootFromInclusionProof

### LINKED ISSUE #1278: [C++, Go] Inclusion Proof fails for leaf_index = 0
Returning a leaf index of 0 is a valid CT response, per the [RFC](https://tools.ietf.org/html/draft-ietf-trans-rfc6962-bis-17#section-10.4.1), and is the index of the first entry.  

SCT:
`{"tree_size":1,"timestamp":1469742447178,"sha256_root_hash":"4OEMvu0pQwiIBmNv8x+7ivc10k6j0yTuSsmRA3ZPmes=","tree_head_signature":"BAMARTBDAiAiVLelb8WoTpu4JnCaiAVFBZyPrVuNrdXJzlHr2qy49QIfbHdVQRYnOjFsBtduv+7NubX5xhLTPEy9nKtRyueqwA=="}`

Proof By Hash:
`/ct/v1/get-proof-by-hash?hash=4OEMvu0pQwiIBmNv8x%2B7ivc10k6j0yTuSsmRA3ZPmes%3D&tree_size=1`
`{"leaf_index":0,"audit_path":[]}`

The python implementation follows the RFC algorithm and verifies, but the Go and C++ implementations do not.

### PR DESCRIPTION
**Pull request by gdbelvin**
Merge PR #1281 first 

RootFromInclusionProof make the assumption that leafs are indexed from
1. However, upon observation from real output from CT server, leafs
appear to be indexed from 0. After inserting a single entry into an
empty tree, the tree size is 1, and the leaf index is 0.

This CL adds a test to the Go Merkle Tree Verifier for this case and
adjusts the verification algorithm to more closely match the python
implementation.

Fixes #1278

### CODE REVIEW

**Comment by gdbelvin** [comment]
@pphaneuf @taknira @Martin2112

**Comment by pphaneuf** [comment]
Unfortunately, with GitHub, it's not very helpful to start PRs based on other PRs, it's best to wait for the first one to be actually merged (you can keep the branch around on your side, ready to be sent in, of course!)...

But #1281 has been merged now, so you should be able to rebase this, and we can take a look.

File: go/merkletree/merkle_verifier.go [hunk 1]
```diff
@@ -46,15 +46,16 @@ func (m MerkleVerifier) VerifyInclusionProof(leafIndex, treeSize int64, proof []
...
 // RootFromInclusionProof calculates the expected tree root given the proof and leaf.
+// leafIndex starts at 0. treeSize starts at 1.
 func (m MerkleVerifier) RootFromInclusionProof(leafIndex, treeSize int64, proof [][]byte, leaf []byte) ([]byte, error) {
-	if leafIndex > treeSize {
+	if leafIndex >= treeSize {
 		return nil, fmt.Errorf("leafIndex %d > treeSize %d", leafIndex, treeSize)
 	}
-	if leafIndex == 0 {
-		return nil, errors.New("leafIndex is zero")
+	if leafIndex < 0 || treeSize < 0 {
```
Comment (pphaneuf) [inline go/merkletree/merkle_verifier.go]: Shouldn't that be `treeSize < 1`?

File: go/merkletree/merkle_verifier.go [hunk 2]
```diff
@@ -46,15 +46,16 @@ func (m MerkleVerifier) VerifyInclusionProof(leafIndex, treeSize int64, proof []
...
+		return nil, errors.New("leafIndex or treeSize is less than zero")
```
Comment (pphaneuf) [inline go/merkletree/merkle_verifier.go]: Might involve separating the errors, or tweaking the message to not mention "zero"...

File: go/merkletree/merkle_verifier_test.go [hunk 3]
```diff
@@ -1,10 +1,13 @@
 package merkletree
 
 import (
+	".."
```
Comment (pphaneuf) [inline go/merkletree/merkle_verifier_test.go]: Huh? What does that even do?!?

Comment (gdbelvin) [inline go/merkletree/merkle_verifier_test.go]: This line imports the `ct` lib. it could be rewritten as 
`import ct ..` or 
`import ct github.com/google/certificate-transparency/go`

What's your preference?

File: go/merkletree/merkle_verifier.go (hunk 1 above)
Comment (gdbelvin) [inline go/merkletree/merkle_verifier.go]: I was following the [python](https://github.com/google/certificate-transparency/blob/master/python/ct/crypto/merkle.py#L482) code.

**Comment by gdbelvin** [comment]
Responded to comments

File: go/merkletree/merkle_verifier_test.go (hunk 3 above)
Comment (pphaneuf) [inline go/merkletree/merkle_verifier_test.go]: I'd prefer the absolute one (I believe that's what is recommended in Effective Go?).

File: go/merkletree/merkle_verifier.go (hunk 1 above)
Comment (pphaneuf) [inline go/merkletree/merkle_verifier.go]: Huh, I think that's a bug in the Python code? You can't possibly have an inclusion proof for an empty tree, *that* is certain! :smiley:

File: go/merkletree/merkle_verifier.go [hunk 4]
```diff
@@ -47,15 +47,16 @@ func (m MerkleVerifier) VerifyInclusionProof(leafIndex, treeSize int64, proof []
 }
 
 // RootFromInclusionProof calculates the expected tree root given the proof and leaf.
+// leafIndex starts at 0. treeSize starts at 1.
 func (m MerkleVerifier) RootFromInclusionProof(leafIndex, treeSize int64, proof [][]byte, leaf []byte) ([]byte, error) {
-	if leafIndex > treeSize {
+	if leafIndex >= treeSize {
```
Comment (pphaneuf) [inline go/merkletree/merkle_verifier.go]: Ah, I hadn't spotted that, good catch! Now, that also implies that leafIndex < treeSize, so therefore, treeSize has to be at least 1, it all falls together...

File: go/merkletree/merkle_verifier.go [hunk 5]
```diff
@@ -47,15 +47,16 @@ func (m MerkleVerifier) VerifyInclusionProof(leafIndex, treeSize int64, proof []
...
 		return nil, fmt.Errorf("leafIndex %d > treeSize %d", leafIndex, treeSize)
 	}
-	if leafIndex == 0 {
-		return nil, errors.New("leafIndex is zero")
+	if leafIndex < 0 || treeSize < 1 {
+		return nil, errors.New("leafIndex < 0 or treeSize < 1")
 	}
 
-	node := leafIndex - 1
+	nodeIndex := leafIndex
```
Comment (pphaneuf) [inline go/merkletree/merkle_verifier.go]: And good call on renaming this. I know the Go folks would probably just call this `n` or `i`, but this code is tricky enough as it is... :stuck_out_tongue:

File: go/merkletree/merkle_verifier_test.go [hunk 6]
```diff
@@ -19,7 +22,7 @@ func verifierCheck(v *MerkleVerifier, leafIndex, treeSize int64, proof [][]byte,
 		return err
 	}
 	if want := root; !bytes.Equal(got, want) {
-		return fmt.Errorf("got root:\n%v\nexpected:\n%v", got, want)
+		return fmt.Errorf("got root:\n%x\nexpected:\n%x", got, want)
```
Comment (pphaneuf) [inline go/merkletree/merkle_verifier_test.go]: I'll let it slide this time, but this looks like a lint warning that's been fixed, unrelated to this PR... :wink:

**Comment by pphaneuf** [comment]
This is LGTM for me, but that `leaf-1` in the test (at the bottom of the diff) makes me think that we've had some fun times where some things are zero-indexed, others are one-indexed, and I keep forgetting which ones are which. :stuck_out_tongue_winking_eye: 

So I'll merge this once Travis is in, but I wouldn't be surprised if something came up about this later on... :worried:

File: go/merkletree/merkle_verifier_test.go (hunk 6 above)
Comment (gdbelvin) [inline go/merkletree/merkle_verifier_test.go]: Not a lint warning. Just makes debugging a bit easier. It prints the byte string out in hex rather than as an array of integers.

**Comment by gdbelvin** [comment]
Yeah, those off by one errors are a ***.

File: go/merkletree/merkle_verifier_test.go (hunk 6 above)
Comment (pphaneuf) [inline go/merkletree/merkle_verifier_test.go]: Ah, good to know, I've wanted that before!
