### PR TITLE
[Go] Implement GetProofByHash

### LINKED ISSUE #1278: [C++, Go] Inclusion Proof fails for leaf_index = 0
Returning a leaf index of 0 is a valid CT response, per the [RFC](https://tools.ietf.org/html/draft-ietf-trans-rfc6962-bis-17#section-10.4.1), and is the index of the first entry.  

SCT:
`{"tree_size":1,"timestamp":1469742447178,"sha256_root_hash":"4OEMvu0pQwiIBmNv8x+7ivc10k6j0yTuSsmRA3ZPmes=","tree_head_signature":"BAMARTBDAiAiVLelb8WoTpu4JnCaiAVFBZyPrVuNrdXJzlHr2qy49QIfbHdVQRYnOjFsBtduv+7NubX5xhLTPEy9nKtRyueqwA=="}`

Proof By Hash:
`/ct/v1/get-proof-by-hash?hash=4OEMvu0pQwiIBmNv8x%2B7ivc10k6j0yTuSsmRA3ZPmes%3D&tree_size=1`
`{"leaf_index":0,"audit_path":[]}`

The python implementation follows the RFC algorithm and verifies, but the Go and C++ implementations do not.

### PR DESCRIPTION
**Pull request by gdbelvin**
This PR includes the code required to fetch inclusion proofs

Contributes to #1159

### CODE REVIEW

**Comment by gdbelvin** [comment]
Thoughts on the best way to test this are welcome.

**Comment by gdbelvin** [comment]
Added tests

**Comment by pphaneuf** [comment]
Another merge crept up, these muddle up the PRs a bit, you should use something along the lines of `git fetch https://github.com/google/certificate-transparency.git master && git rebase FETCH_BASE` (could be simplified a bit, but the exact command-line would depend on what the remotes on your local repo are named).

**Comment by gdbelvin** [comment]
Rebased as requested. PTAL

**Comment by gdbelvin** [comment]
Rebased again. PTAL 
@pphaneuf

File: go/client/logclient.go [hunk 1]
```diff
@@ -105,6 +101,19 @@ type getEntryAndProofResponse struct {
 	AuditPath []string `json:"audit_path"` // the corresponding proof
 }
 
+type getProofByHashResponse struct {
+	LeafIndex    int      `json:"leaf_index"` // The 0-based index of the end entity corresponding to the "hash" parameter.
+	AuditPath    []string `json:"audit_path"` // An array of base64-encoded Merkle Tree nodes proving the inclusion of the chosen certificate.
```
Comment (pphaneuf) [inline go/client/logclient.go]: Does it work if you make this field a `[][]byte` instead (and strip out the base64 decoding at line 423)?

File: go/client/logclient.go [hunk 2]
```diff
@@ -105,6 +101,19 @@ type getEntryAndProofResponse struct {
...
+	Success      bool     `json:"success"`
+	ErrorMessage string   `json:"error_message"`
+}
+
+// addJSONRequest represents the JSON request body sent ot the add-json CT
```
Comment (pphaneuf) [inline go/client/logclient.go]: Why did this move?

File: go/client/logclient.go [hunk 3]
```diff
@@ -105,6 +101,19 @@ type getEntryAndProofResponse struct {
 	AuditPath []string `json:"audit_path"` // the corresponding proof
 }
 
+type getProofByHashResponse struct {
+	LeafIndex    int      `json:"leaf_index"` // The 0-based index of the end entity corresponding to the "hash" parameter.
```
Comment (pphaneuf) [inline go/client/logclient.go]: We're using `int64` for leaf indices in general, is there a problem with the JSON parser that prevents using that?

File: go/client/logclient.go [hunk 4]
```diff
@@ -386,3 +403,28 @@ func (c *LogClient) GetEntries(start, end int64) ([]ct.LogEntry, error) {
...
+func (c *LogClient) GetProofByHash(hash []byte, treeSize uint64) (ct.AuditPath, error) {
+	var resp getProofByHashResponse
+	b64Hash := url.QueryEscape(base64.StdEncoding.EncodeToString(hash))
+	u := fmt.Sprintf("%s%s?tree_size=%d&hash=%v", c.uri, GetProofByHashPath, treeSize, b64Hash)
+	log.Printf("%v", u)
+	err := c.fetchAndParse(u, &resp)
+	if err != nil {
+		return nil, err
+	}
+	if resp.ErrorMessage != "" {
```
Comment (pphaneuf) [inline go/client/logclient.go]: I think you might be disappointed by some recent developments in `fetchAndParse` (and might need a further rebase, at the minimum)...

File: go/serialization.go [hunk 5]
```diff
@@ -126,10 +130,10 @@ func readASN1CertList(r io.Reader, totalLenBytes int, elementLenBytes int) ([]AS
 // Returns a non-nil error if there was a problem.
 func ReadTimestampedEntryInto(r io.Reader, t *TimestampedEntry) error {
 	var err error
```
Comment (pphaneuf) [inline go/serialization.go]: That line might not be needed anymore, with your other changes? (I like your way better!)

File: go/serialization.go [hunk 6]
```diff
@@ -144,13 +148,48 @@ func ReadTimestampedEntryInto(r io.Reader, t *TimestampedEntry) error {
 		if t.PrecertEntry.TBSCertificate, err = readVarBytes(r, PreCertificateLengthBytes); err != nil {
 			return err
 		}
+	case XJSONLogEntryType:
+		if t.JSONData, err = readVarBytes(r, JSONLengthBytes); err != nil {
```
Comment (pphaneuf) [inline go/serialization.go]: But if you do that, might have to make the `=` into a `:=` as well?

**Comment by pphaneuf** [comment]
Hmm... Am I missing some reference from `logclient.go`, or are the changes in `serialization.go`, `types.go`, and `signatures.go` are not related at all to what's in the description of this PR? Other change got mixed in?

File: go/serialization.go (hunk 6 above)
Comment (gdbelvin) [inline go/serialization.go]: Kept the original scheme.  Has to do with `struct.field` not being something you can `:=` assign.

**Comment by gdbelvin** [comment]
The changes in `types.go` and `serialization.go` allow a client to compute what the right hash of a given `SCT` and `json` so that the client can use the `GetByHash` function.   I decided to separate the compute hash and get-by-hash functions in case the client has the hash available directly. 

Cleaned up, rebased, updated. PTAL.

**Comment by gdbelvin** [comment]
PTAL

**Comment by gdbelvin** [comment]
Fixes #1278

File: go/client/logclient.go [hunk 7]
```diff
@@ -85,13 +82,21 @@ type getAcceptedRootsResponse struct {
...
 	LeafInput string   `json:"leaf_input"` // the entry itself
 	ExtraData string   `json:"extra_data"` // any chain provided when the entry was added to the log
 	AuditPath []string `json:"audit_path"` // the corresponding proof
 }
 
+// GetProofByHashResponse represents the JSON response to the CT get-proof-by-hash method.
+type GetProofByHashResponse struct {
+	LeafIndex    int64    `json:"leaf_index"` // The 0-based index of the end entity corresponding to the "hash" parameter.
+	AuditPath    [][]byte `json:"audit_path"` // An array of base64-encoded Merkle Tree nodes proving the inclusion of the chosen certificate.
+	Success      bool     `json:"success"`
```
Comment (eranmes) [inline go/client/logclient.go]: I suggest getting rid of this and the ErrorMessage because the GetProofByHashResponse should not be created if there was a failure.

File: go/merkletree/merkle_verifier_test.go [hunk 8]
```diff
@@ -299,9 +310,30 @@ func getConsistencyProofs() []consistencyTestVector {
...
+	googleLeaf := new(bytes.Buffer)
+	// Insert leaf cert into local CT instance:
+	// curl -X POST localhost:8088/ct/v1/add-chain -d '{"chain": [...]}'
+	// {"sct_version":0,"id":"3xwuwRUAlFJHqWFoMl3cXHlZ6PfG04j8AC4LvT9012Q=","timestamp":1469742100562,"extensions":"","signature":"BAMARjBEAiBCJXqOLwGlXdh749\/dUiWjp8AlwQUrdg2+PCqEn9lFTAIgfw8o4Q4b0YJQfpemrN4SoBNVZ5IJMAmehk\/TSZexenc="}
+	// Query by hash for the inclusion proof:
+	// curl localhost:8088/ct/v1/get-proof-by-hash?hash=4OEMvu0pQwiIBmNv8x%2B7ivc10k6j0yTuSsmRA3ZPmes%3D&tree_size=1
+	// {"leaf_index":0,"audit_path":[]}
+
+	// Compute leaf value from timestamp
+	if err := ct.SerializeV1SCTMerkleTreeLeafX509(googleLeaf, uint64(1469742100562), googlePEM); err != nil {
```
Comment (eranmes) [inline go/merkletree/merkle_verifier_test.go]: I believe you could use test data to load certificate, SCT from here:
https://github.com/google/certificate-transparency/tree/master/test/testdata
The test will then be much simpler and will only test that SerializeV1SCTMerkleTreeLeafX509 correctly serializes.

**Comment by gdbelvin** [comment]
@pphaneuf @taknira 

Cleaned up this PR, and made it exclusively about fetching the inclusion proof.

File: go/types.go [hunk 9]
```diff
@@ -319,6 +319,7 @@ type TimestampedEntry struct {
 	X509Entry    ASN1Cert
 	JSONData     []byte
 	PrecertEntry PreCert
+	JSONData     []byte
```
Comment (pphaneuf) [inline go/types.go]: Same as the one at line 320? This causes a build error. :wink:

**Comment by gdbelvin** [comment]
Fixed

File: go/client/logclient.go [hunk 10]
```diff
@@ -308,3 +317,12 @@ func (c *LogClient) GetSTH() (sth *ct.SignedTreeHead, err error) {
 	sth.TreeHeadSignature = *ds
 	return
 }
+
+// GetProofByHash returns an audit path for the hash of an SCT.
+func (c *LogClient) GetProofByHash(hash []byte, treeSize uint64) (GetProofByHashResponse, error) {
```
Comment (pphaneuf) [inline go/client/logclient.go]: Big enough that `GetProofByHashResponse` should be returned as a pointer?

Comment (pphaneuf) [inline go/client/logclient.go]: That would also allow returning `nil` in the case of an error.

File: go/client/logclient.go [hunk 11]
```diff
@@ -308,3 +317,12 @@ func (c *LogClient) GetSTH() (sth *ct.SignedTreeHead, err error) {
...
+	var resp GetProofByHashResponse
```
Comment (pphaneuf) [inline go/client/logclient.go]: I'd move that to right before it's needed (before `fetchAndParse`).

File: go/client/logclient.go (hunk 10 above)
Comment (pphaneuf) [inline go/client/logclient.go]: We have some historical baggage, but might as well take a `context.Context` as the first parameter on new methods?

File: go/types.go [hunk 12]
```diff
@@ -317,8 +317,8 @@ type TimestampedEntry struct {
 	Timestamp    uint64
 	EntryType    LogEntryType
 	X509Entry    ASN1Cert
-	JSONData     []byte
 	PrecertEntry PreCert
+	JSONData     []byte
```
Comment (pphaneuf) [inline go/types.go]: Maybe you could move it up to where it was, to avoid the noise?

**Comment by pphaneuf** [comment]
Done with this round of review, should be straightforward... :smiley:

File: go/client/logclient.go [hunk 13]
```diff
@@ -319,10 +319,12 @@ func (c *LogClient) GetSTH() (sth *ct.SignedTreeHead, err error) {
 }
 
 // GetProofByHash returns an audit path for the hash of an SCT.
-func (c *LogClient) GetProofByHash(hash []byte, treeSize uint64) (GetProofByHashResponse, error) {
-	var resp GetProofByHashResponse
+func (c *LogClient) GetProofByHash(ctx context.Context, hash []byte, treeSize uint64) (*GetProofByHashResponse, error) {
+	resp := new(GetProofByHashResponse)
```
Comment (pphaneuf) [inline go/client/logclient.go]: Oops, you've seen my comment in #1285? I like `var` better than `new`: it seems there's no case where `new` does anything that you can't do with `var` and `&`, so I'd rather have just one way of doing things, for consistency, and let the compiler do the escape analysis...

And either way, I'd still want it declared "at the last moment". :wink:

File: go/client/logclient_test.go [hunk 14]
```diff
@@ -275,7 +275,7 @@ func TestGetProofByHash(t *testing.T) {
 	}
 
 	for _, tc := range tests {
-		resp, err := c.GetProofByHash(tc.hash, tc.treesize)
+		resp, err := c.GetProofByHash(context.TODO(), tc.hash, tc.treesize)
```
Comment (pphaneuf) [inline go/client/logclient_test.go]: I guess that in a test, it should be `context.Background()`? Not like we'll refactor in the future to get the context from somewhere else, right?

File: go/serialization.go [hunk 15]
```diff
@@ -147,6 +147,10 @@ func ReadTimestampedEntryInto(r io.Reader, t *TimestampedEntry) error {
 		if t.PrecertEntry.TBSCertificate, err = readVarBytes(r, PreCertificateLengthBytes); err != nil {
 			return err
 		}
+	case XJSONLogEntryType:
```
Comment (pphaneuf) [inline go/serialization.go]: I kind of missed this in the previous round, but, er, this has nothing to do with "implementing GetProofByHash", doesn't it? :wink:

Comment (gdbelvin) [inline go/serialization.go]: Would you like it moved to a different PR? It was so nice to sneak it into this one !

Comment (pphaneuf) [inline go/serialization.go]: Yeah, this is making this PR all icky! :laughing:

**Comment by pphaneuf** [comment]
LGTM, waiting on Travis to merge.

**Comment by pphaneuf** [comment]
Will need a rebase (and you can squash into one commit, if you want).

**Comment by gdbelvin** [comment]
Rebased on master
